In [1]:
import market
import random
random.seed = 9
series1, rd_series1 = market.dividend_series(10)
print(series1)
print(rd_series1)
print('--')
random.seed = 9
series2, rd_series2 = market.dividend_series(10)
print(series2)
print(rd_series2)
''' Those two series are different while they should be equal.
The first term is equal, okay. But not afterwards.
INITIAL_DIVIDEND = 0.003983
Source of the error: rdiv. '''

[0.003983, 0.0040013168737743675, 0.004012101674878107, 0.004055353203791689, 0.004079931881677702, 0.0040861767201442085, 0.004080067137640575, 0.0040794459557312755, 0.004082562698550061, 0.004078962508353057]
[0, 0.7237627808852891, 0.4215994199574505, 1.705046154303899, 0.9558536631183882, 0.23671066015433448, -0.24362120681478786, -0.030436857825214332, 0.11501479132817069, -0.14625690166424654]
--
[0.003983, 0.003945532475877125, 0.0039535967544927185, 0.0039733438877804115, 0.00394639136845731, 0.003984659946920604, 0.004001671709297465, 0.004024970505939726, 0.00401635270488742, 0.004002616232183042]
[0, -1.4995610033011681, 0.3181910159147736, 0.786619960260988, -1.0830891578336035, 1.5330997342902226, 0.6714642593079839, 0.9179878115640886, -0.34615483446513473, -0.5491980104531117]


' Those two series are different while they should be equal.\nThe first term is equal, okay. But not afterwards.\nINITIAL_DIVIDEND = 0.003983\nSource of the error: rdiv. '

In [2]:
import random 
random.seed = 9
print(random.normalvariate(0, 1))
print(random.normalvariate(0, 1))
print(random.normalvariate(0, 1))
print('---')
random.seed = 9
print(random.normalvariate(0, 1))
print(random.normalvariate(0, 1))
print(random.normalvariate(0, 1))
print('---')
random.seed = 10
print(random.normalvariate(0, 1))
print(random.normalvariate(0, 1))
print(random.normalvariate(0, 1))

-0.36772963970464123
0.4604679731875619
-0.9188523422663127
---
0.6132392060210957
-1.937915034443408
0.34706060239789144
---
-0.07343582540284929
-0.5884642819901214
0.5247481924876943


In [6]:
import random

random.seed(10)
print(random.random())

random.seed = 10
print(random.random())

TypeError: 'int' object is not callable

In [8]:
import numpy as np 
np.random.seed(42)
print(np.random.rand(5))
print('---')
np.random.seed(42)
print(np.random.rand(5))
print('---')
np.random.seed(43)
print(np.random.rand(5))


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
---
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
---
[0.11505457 0.60906654 0.13339096 0.24058962 0.32713906]


In [9]:
from parameters import *

def draw_dividend(dividend):
    DIVIDEND_GROWTH_RATE = ((1 + DIVIDEND_GROWTH_RATE_G) ** (1 / TRADING_DAYS)) - 1
    random_dividend = np.random.normal(0, 1)
    if len(random_dividend_history) > DIVIDEND_ATC_TAU:
        random_dividend = (1 - DIVIDEND_AUTOCORRELATION ** 2) * random_dividend + DIVIDEND_AUTOCORRELATION * random_dividend_history[- 1 - DIVIDEND_ATC_TAU]
    dividend = abs(dividend + DIVIDEND_GROWTH_RATE * dividend + DIVIDEND_GROWTH_VOLATILITY * dividend * random_dividend)
    return dividend, random_dividend

def dividend_series(horizon):
    history, rdiv_history = [], []
    dividend = INITIAL_DIVIDEND
    history.append(dividend)
    rdiv_history.append(0)
    for i in range(horizon-1):
        dividend, rdiv = draw_dividend(dividend)
        history.append(dividend)
        rdiv_history.append(rdiv)
    return history, rdiv_history

np.random.seed(42)
print(dividend_series(10)[0])
print(dividend_series(10)[0])
print('---')
np.random.seed(42)
print(dividend_series(10)[0])
print(dividend_series(10)[0])
print('---')
np.random.seed(9)
print(dividend_series(10)[0])
print(dividend_series(10)[0])

[0.003983, 0.003995620100731487, 0.003992297754567234, 0.004008744186864852, 0.004047363115512206, 0.004041552958218387, 0.0040357515596324, 0.004076058999135711, 0.004095925183265008, 0.004083973583115859]
[0.003983, 0.003996770398956137, 0.003985260616075088, 0.003973725934949621, 0.003979939671097742, 0.003932128471012132, 0.0038895573813163414, 0.003875933847679244, 0.0038513575196515446, 0.003859133635186435]
---
[0.003983, 0.003995620100731487, 0.003992297754567234, 0.004008744186864852, 0.004047363115512206, 0.004041552958218387, 0.0040357515596324, 0.004076058999135711, 0.004095925183265008, 0.004083973583115859]
[0.003983, 0.003996770398956137, 0.003985260616075088, 0.003973725934949621, 0.003979939671097742, 0.003932128471012132, 0.0038895573813163414, 0.003875933847679244, 0.0038513575196515446, 0.003859133635186435]
---
[0.003983, 0.003983185087850207, 0.003976077213664045, 0.003948280176959172, 0.003948115661916124, 0.003938861409206962, 0.003927078771353398, 0.00388969768

In [2]:
import timeit
import math
import numpy as np

%timeit math.log(10)
# 158 ns ± 6.16 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

%timeit np.log(10)
# 1.64 µs ± 93.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit math.exp(3)
# 146 ns ± 8.57 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

%timeit np.exp(3)
# 1.72 µs ± 78.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

79.5 ns ± 0.405 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
774 ns ± 41.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
103 ns ± 6.29 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
730 ns ± 71.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [3]:
%timeit math.tanh(3)
# 119 ns ± 4.75 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
%timeit np.tanh(3)
# 687 ns ± 2.54 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

119 ns ± 4.75 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
687 ns ± 2.54 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
from main import * 
wealth_coordinates = [1/3, 1/3, 1/3]
time = 100
agents = 10

seed = random.randint(0,10)
np.random.seed(seed)
df,pop = main("between", 'scholl', 'esl.true', False, time, 0, agents, 0, wealth_coordinates, tqdm_display=True, reset_wealth = False)
np.random.seed(seed)
df2,pop2 = main("between", 'scholl', 'esl.true', False, time, 0, agents, 0, wealth_coordinates, tqdm_display=True, reset_wealth = False)

print(df['Price'].iloc[-1])
print(df2['Price'].iloc[-1])

print(pop)
print(pop2)

85.78
85.78
[[113.65153106424783], [113.65153106424783], [2], [113.65153106424783], [113.65153106424783], [113.65153106424783], [2], [113.65153106424783], [2], [113.65153106424783]]
[[113.65153106424783], [113.65153106424783], [2], [113.65153106424783], [113.65153106424783], [113.65153106424783], [2], [113.65153106424783], [2], [113.65153106424783]]


In [2]:
import time
import random
import line_profiler
profile = line_profiler.LineProfiler()

@profile
def very_slow_random_generator():
    time.sleep(5)
    arr = [random.randint(1,100) for i in range(100000)]
    return sum(arr) / len(arr)

@profile
def slow_random_generator():
    time.sleep(2)
    arr = [random.randint(1,100) for i in range(100000)]
    return sum(arr) / len(arr)

@profile
def fast_random_generator():
    time.sleep(1)
    arr = [random.randint(1,100) for i in range(100000)]
    return sum(arr) / len(arr)

@profile
def main_func():
    result = fast_random_generator()
    print(result)

    result = slow_random_generator()
    print(result)

    result = very_slow_random_generator()
    print(result)

main_func()

50.40008
50.46492
50.6027


In [4]:
import creation 

pop, asset_supply = creation.CreatePop(10, 'scholl', [1/3,1/3,1/3])
print(pop)
for ind in pop:
    print(type(ind))
    print(type(ind[0]))

[[100], [100], [2], [100], [2], [2], [100], [100], [2], [2]]
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
<class 'deap.creator.ind'>
<class 'int'>
