In [45]:
import pandas as pd

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

standard_coord_NT_Return = standard_coord['NT_MonReturns'].mean()
standard_coord_VI_Return = standard_coord['VI_MonReturns'].mean()
standard_coord_TF_Return = standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)

std_std_NT = standard_coord['NT_MonReturns'].std()
std_std_VI = standard_coord['VI_MonReturns'].std()
std_std_TF = standard_coord['TF_MonReturns'].std()

print(std_std_NT, std_std_VI, std_std_TF)
print('----')
NT_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_NT_bump.csv")

NT_bump_NT_Return = NT_bump_coord['NT_MonReturns'].mean()
NT_bump_VI_Return = NT_bump_coord['VI_MonReturns'].mean()
NT_bump_TF_Return = NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

NT_bump_NT_std = NT_bump_coord['NT_MonReturns'].std()
NT_bump_VI_std = NT_bump_coord['VI_MonReturns'].std()
NT_bump_TF_std = NT_bump_coord['TF_MonReturns'].std()

print(NT_bump_NT_std, NT_bump_VI_std, NT_bump_TF_std)
print('----')

VI_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_VI_bump.csv")

VI_bump_NT_Return = VI_bump_coord['NT_MonReturns'].mean()
VI_bump_VI_Return = VI_bump_coord['VI_MonReturns'].mean()
VI_bump_TF_Return = VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

VI_bump_NT_std = VI_bump_coord['NT_MonReturns'].std()
VI_bump_VI_std = VI_bump_coord['VI_MonReturns'].std()
VI_bump_TF_std = VI_bump_coord['TF_MonReturns'].std()

print(VI_bump_NT_std, VI_bump_VI_std, VI_bump_TF_std)
print('----')

TF_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_TF_bump.csv")

TF_bump_NT_Return = TF_bump_coord['NT_MonReturns'].mean()
TF_bump_VI_Return = TF_bump_coord['VI_MonReturns'].mean()
TF_bump_TF_Return = TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)

TF_bump_NT_std = TF_bump_coord['NT_MonReturns'].std()
TF_bump_VI_std = TF_bump_coord['VI_MonReturns'].std()
TF_bump_TF_std = TF_bump_coord['TF_MonReturns'].std()

print(TF_bump_NT_std, TF_bump_VI_std, TF_bump_TF_std)
print('----')



0.00042179040828959957 0.0009116512787118482 0.00152549933539493
0.03682370574628645 0.041682553748021926 0.04390121877373065
----
0.000978443519793037 0.0014655542955764194 0.0009967368853568254
0.03359634339311825 0.02152251982944608 0.01817126990984914
----
-1.384647579336998e-06 0.0008543410710871386 0.0011881229891518449
0.04050686930965046 0.028891460378257353 0.024681740519116806
----
0.0011899543416383008 0.0013398329777764325 0.0009002673669615772
0.040221283601115966 0.021630802258993193 0.02175906801504598
----


In [46]:
import numpy as np
np.set_printoptions(suppress=True)
h = 2/256
GainMatrix = np.zeros((3,3))

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''


[[ 0.071 -0.054  0.098]
 [ 0.071 -0.007  0.055]
 [-0.068 -0.043 -0.08 ]]


' export later to latex table '

In [57]:
from tabulate import tabulate
from texttable import Texttable
import latextable

rows = [['', 'NT', 'VI', 'TF'],
        ['NT', str(GainMatrix[0,0]), str(GainMatrix[0,1]), str(GainMatrix[0,2])],
        ['VI', str(GainMatrix[1,0]), str(GainMatrix[1,1]), str(GainMatrix[1,2])],
        ['TF', str(GainMatrix[2,0]), str(GainMatrix[2,1]), str(GainMatrix[2,2])]]

table = Texttable()
table.set_cols_align(["c"] * 4)
table.set_deco(Texttable.HEADER | Texttable.VLINES)
table.add_rows(rows)


print('\nTexttable Table:')
print(table.draw())
# print(latextable.draw_latex(table, caption="Gain matrix at the equal wealth coordinates"))


Texttable Table:
   |   NT   |   VI   |  TF  
===+========+========+======
NT | 0.033  | -0.055 | 0.040
VI | 0.056  | 0.009  | 0.045
TF | -0.019 | -0.002 | 0.023


In [59]:
print(latextable.draw_latex(table, caption="Gain matrix at the equal wealth coordinates"))

\begin{table}
	\begin{center}
		\begin{tabular}{c|c|c|c}
			 & NT & VI & TF \\
			\hline
			NT & 0.033 & -0.055 & 0.040 \\
			VI & 0.056 & 0.009 & 0.045 \\
			TF & -0.019 & -0.002 & 0.023 \\
		\end{tabular}
	\end{center}
	\caption{Gain matrix at the equal wealth coordinates}
\end{table}


In [53]:
''' Gain matrix estimation without outliers '''
np.set_printoptions(suppress=True)
margin = 3

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['NT_MonReturns']-standard_coord['NT_MonReturns'].mean()) <= (margin*standard_coord['NT_MonReturns'].std())]
standard_coord_NT_Return = new_standard_coord['NT_MonReturns'].mean()

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['VI_MonReturns']-standard_coord['VI_MonReturns'].mean()) <= (margin*standard_coord['VI_MonReturns'].std())]
standard_coord_VI_Return = new_standard_coord['VI_MonReturns'].mean()

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['TF_MonReturns']-standard_coord['TF_MonReturns'].mean()) <= (margin*standard_coord['TF_MonReturns'].std())]
standard_coord_TF_Return = new_standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)


new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['NT_MonReturns']-NT_bump_coord['NT_MonReturns'].mean()) <= (margin*NT_bump_coord['NT_MonReturns'].std())]
NT_bump_NT_Return = new_NT_bump_coord['NT_MonReturns'].mean()

new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['VI_MonReturns']-NT_bump_coord['VI_MonReturns'].mean()) <= (margin*NT_bump_coord['VI_MonReturns'].std())]
NT_bump_VI_Return = new_NT_bump_coord['VI_MonReturns'].mean()

new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['TF_MonReturns']-NT_bump_coord['TF_MonReturns'].mean()) <= (margin*NT_bump_coord['TF_MonReturns'].std())]
NT_bump_TF_Return = new_NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['NT_MonReturns']-VI_bump_coord['NT_MonReturns'].mean()) <= (margin*VI_bump_coord['NT_MonReturns'].std())]
VI_bump_NT_Return = new_VI_bump_coord['NT_MonReturns'].mean()

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['VI_MonReturns']-VI_bump_coord['VI_MonReturns'].mean()) <= (margin*VI_bump_coord['VI_MonReturns'].std())]
VI_bump_VI_Return = new_VI_bump_coord['VI_MonReturns'].mean()

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['TF_MonReturns']-VI_bump_coord['TF_MonReturns'].mean()) <= (margin*VI_bump_coord['TF_MonReturns'].std())]
VI_bump_TF_Return = new_VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = TF_bump_coord[np.abs(TF_bump_coord['NT_MonReturns']-TF_bump_coord['NT_MonReturns'].mean()) <= (margin*TF_bump_coord['NT_MonReturns'].std())]
TF_bump_NT_Return = new_TF_bump_coord['NT_MonReturns'].mean()

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = TF_bump_coord[np.abs(TF_bump_coord['VI_MonReturns']-TF_bump_coord['VI_MonReturns'].mean()) <= (margin*TF_bump_coord['VI_MonReturns'].std())]
TF_bump_VI_Return = new_TF_bump_coord['VI_MonReturns'].mean()

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = VI_bump_coord[np.abs(TF_bump_coord['TF_MonReturns']-TF_bump_coord['TF_MonReturns'].mean()) <= (margin*TF_bump_coord['TF_MonReturns'].std())]
TF_bump_TF_Return = new_TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)




0.00027724157013802925 0.0008252865549118169 0.001005621162520661
0.0005319514717276877 0.0012638029138254594 0.0008588829030353721
-0.0001531543313599827 0.0008977230988897337 0.0009871267598864004
0.0005910139721648736 0.0011734473834815397 0.0011869592466888842


In [54]:
np.set_printoptions(suppress=True)
GainMatrix = np.zeros((3,3))
h = 2/256

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''

[[ 0.033 -0.055  0.04 ]
 [ 0.056  0.009  0.045]
 [-0.019 -0.002  0.023]]


' export later to latex table '

In [ ]:
from tabulate import tabulate
from texttable import Texttable
import latextable

rows = [['', 'NT', 'VI', 'TF'],
        ['NT', str(GainMatrix[0,0]), str(GainMatrix[0,1]), str(GainMatrix[0,2])],
        ['VI', str(GainMatrix[1,0]), str(GainMatrix[1,1]), str(GainMatrix[1,2])],
        ['TF', str(GainMatrix[2,0]), str(GainMatrix[2,1]), str(GainMatrix[2,2])]]

table = Texttable()
table.set_cols_align(["c"] * 4)
table.set_deco(Texttable.HEADER | Texttable.VLINES)
table.add_rows(rows)


print('\nTexttable Table:')
print(table.draw())
print(latextable.draw_latex(table, caption="Gain matrix at the equal wealth coordinates"))