In [105]:
import pandas as pd

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

standard_coord_NT_Return = standard_coord['NT_MonReturns'].mean()
standard_coord_VI_Return = standard_coord['VI_MonReturns'].mean()
standard_coord_TF_Return = standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)

std_std_NT = standard_coord['NT_MonReturns'].std()
std_std_VI = standard_coord['VI_MonReturns'].std()
std_std_TF = standard_coord['TF_MonReturns'].std()

print(std_std_NT, std_std_VI, std_std_TF)
print('----')
NT_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_NT_bump.csv")

NT_bump_NT_Return = NT_bump_coord['NT_MonReturns'].mean()
NT_bump_VI_Return = NT_bump_coord['VI_MonReturns'].mean()
NT_bump_TF_Return = NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

NT_bump_NT_std = NT_bump_coord['NT_MonReturns'].std()
NT_bump_VI_std = NT_bump_coord['VI_MonReturns'].std()
NT_bump_TF_std = NT_bump_coord['TF_MonReturns'].std()

print(NT_bump_NT_std, NT_bump_VI_std, NT_bump_TF_std)
print('----')

VI_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_VI_bump.csv")

VI_bump_NT_Return = VI_bump_coord['NT_MonReturns'].mean()
VI_bump_VI_Return = VI_bump_coord['VI_MonReturns'].mean()
VI_bump_TF_Return = VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

VI_bump_NT_std = VI_bump_coord['NT_MonReturns'].std()
VI_bump_VI_std = VI_bump_coord['VI_MonReturns'].std()
VI_bump_TF_std = VI_bump_coord['TF_MonReturns'].std()

print(VI_bump_NT_std, VI_bump_VI_std, VI_bump_TF_std)
print('----')

TF_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_TF_bump.csv")

TF_bump_NT_Return = TF_bump_coord['NT_MonReturns'].mean()
TF_bump_VI_Return = TF_bump_coord['VI_MonReturns'].mean()
TF_bump_TF_Return = TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)

TF_bump_NT_std = TF_bump_coord['NT_MonReturns'].std()
TF_bump_VI_std = TF_bump_coord['VI_MonReturns'].std()
TF_bump_TF_std = TF_bump_coord['TF_MonReturns'].std()

print(TF_bump_NT_std, TF_bump_VI_std, TF_bump_TF_std)
print('----')



0.0013979664233541736 0.0009706173853589997 0.0009101640480326183
0.014028209538170435 0.01084346904105246 0.011677310198846868
----
0.001769632597187723 0.0013012075143569804 0.0013123122799314547
0.013456879174143751 0.011851207911038397 0.011437415365975305
----
0.0013843095443830695 0.0008069291589800165 0.0007646311162212165
0.013285073532542359 0.010642361987667343 0.011865337177337098
----
0.0015230409529323186 0.0010741624135937502 0.0009987748316898802
0.01341616159533029 0.01124899068293573 0.011835890782948196
----


In [106]:
import numpy as np
np.set_printoptions(suppress=True)
h = 0.02
GainMatrix = np.zeros((3,3))

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''


[[ 0.019 -0.001  0.006]
 [ 0.017 -0.008  0.005]
 [ 0.02  -0.007  0.004]]


' export later to latex table '

In [107]:
''' Gain matrix estimation without outliers '''
np.set_printoptions(suppress=True)
margin = 10

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['NT_MonReturns']-standard_coord['NT_MonReturns'].mean()) <= (margin*standard_coord['NT_MonReturns'].std())]
standard_coord_NT_Return = new_standard_coord['NT_MonReturns'].mean()

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['VI_MonReturns']-standard_coord['VI_MonReturns'].mean()) <= (margin*standard_coord['VI_MonReturns'].std())]
standard_coord_VI_Return = new_standard_coord['VI_MonReturns'].mean()

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['TF_MonReturns']-standard_coord['TF_MonReturns'].mean()) <= (margin*standard_coord['TF_MonReturns'].std())]
standard_coord_TF_Return = new_standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)


new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['NT_MonReturns']-NT_bump_coord['NT_MonReturns'].mean()) <= (margin*NT_bump_coord['NT_MonReturns'].std())]
NT_bump_NT_Return = new_NT_bump_coord['NT_MonReturns'].mean()

new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['VI_MonReturns']-NT_bump_coord['VI_MonReturns'].mean()) <= (margin*NT_bump_coord['VI_MonReturns'].std())]
NT_bump_VI_Return = new_NT_bump_coord['VI_MonReturns'].mean()

new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['TF_MonReturns']-NT_bump_coord['TF_MonReturns'].mean()) <= (margin*NT_bump_coord['TF_MonReturns'].std())]
NT_bump_TF_Return = new_NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['NT_MonReturns']-VI_bump_coord['NT_MonReturns'].mean()) <= (margin*VI_bump_coord['NT_MonReturns'].std())]
VI_bump_NT_Return = new_VI_bump_coord['NT_MonReturns'].mean()

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['VI_MonReturns']-VI_bump_coord['VI_MonReturns'].mean()) <= (margin*VI_bump_coord['VI_MonReturns'].std())]
VI_bump_VI_Return = new_VI_bump_coord['VI_MonReturns'].mean()

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['TF_MonReturns']-VI_bump_coord['TF_MonReturns'].mean()) <= (margin*VI_bump_coord['TF_MonReturns'].std())]
VI_bump_TF_Return = new_VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = TF_bump_coord[np.abs(TF_bump_coord['NT_MonReturns']-TF_bump_coord['NT_MonReturns'].mean()) <= (margin*TF_bump_coord['NT_MonReturns'].std())]
TF_bump_NT_Return = new_TF_bump_coord['NT_MonReturns'].mean()

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = TF_bump_coord[np.abs(TF_bump_coord['VI_MonReturns']-TF_bump_coord['VI_MonReturns'].mean()) <= (margin*TF_bump_coord['VI_MonReturns'].std())]
TF_bump_VI_Return = new_TF_bump_coord['VI_MonReturns'].mean()

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = VI_bump_coord[np.abs(TF_bump_coord['TF_MonReturns']-TF_bump_coord['TF_MonReturns'].mean()) <= (margin*TF_bump_coord['TF_MonReturns'].std())]
TF_bump_TF_Return = new_TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)




0.0013979664233541736 0.0009706173853589997 0.0009101640480326183
0.001769632597187723 0.0013012075143569804 0.0013123122799314547
0.0013843095443830695 0.0008069291589800165 0.0007646311162212165
0.0015230409529323186 0.0010741624135937502 0.0007646311162212165


In [108]:
np.set_printoptions(suppress=True)
GainMatrix = np.zeros((3,3))
h = 0.02

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''

[[ 0.019 -0.001  0.006]
 [ 0.017 -0.008  0.005]
 [ 0.02  -0.007 -0.007]]


' export later to latex table '