In [81]:
import pandas as pd

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

standard_coord_NT_Return = standard_coord['NT_MonReturns'].mean()
standard_coord_VI_Return = standard_coord['VI_MonReturns'].mean()
standard_coord_TF_Return = standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)

std_std_NT = standard_coord['NT_MonReturns'].std()
std_std_VI = standard_coord['VI_MonReturns'].std()
std_std_TF = standard_coord['TF_MonReturns'].std()

print(std_std_NT, std_std_VI, std_std_TF)
print('----')
NT_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_NT_bump.csv")

NT_bump_NT_Return = NT_bump_coord['NT_MonReturns'].mean()
NT_bump_VI_Return = NT_bump_coord['VI_MonReturns'].mean()
NT_bump_TF_Return = NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

NT_bump_NT_std = NT_bump_coord['NT_MonReturns'].std()
NT_bump_VI_std = NT_bump_coord['VI_MonReturns'].std()
NT_bump_TF_std = NT_bump_coord['TF_MonReturns'].std()

print(NT_bump_NT_std, NT_bump_VI_std, NT_bump_TF_std)
print('----')

VI_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_VI_bump.csv")

VI_bump_NT_Return = VI_bump_coord['NT_MonReturns'].mean()
VI_bump_VI_Return = VI_bump_coord['VI_MonReturns'].mean()
VI_bump_TF_Return = VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

VI_bump_NT_std = VI_bump_coord['NT_MonReturns'].std()
VI_bump_VI_std = VI_bump_coord['VI_MonReturns'].std()
VI_bump_TF_std = VI_bump_coord['TF_MonReturns'].std()

print(VI_bump_NT_std, VI_bump_VI_std, VI_bump_TF_std)
print('----')

TF_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_TF_bump.csv")

TF_bump_NT_Return = TF_bump_coord['NT_MonReturns'].mean()
TF_bump_VI_Return = TF_bump_coord['VI_MonReturns'].mean()
TF_bump_TF_Return = TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)

TF_bump_NT_std = TF_bump_coord['NT_MonReturns'].std()
TF_bump_VI_std = TF_bump_coord['VI_MonReturns'].std()
TF_bump_TF_std = TF_bump_coord['TF_MonReturns'].std()

print(TF_bump_NT_std, TF_bump_VI_std, TF_bump_TF_std)
print('----')



0.15411153991233995 0.0014533736315519277 0.11487733347430663
32.81620739307097 0.07947882532718152 53.47361707912419
----
0.4194376472745362 0.0033619365635064328 0.09606865948456644
39.04614333424752 0.26688651018747284 30.150435218552055
----
0.06676392715404163 -0.0019722304557659 0.0020272325639243698
29.264868232033564 0.09160408211082029 0.05710972986525674
----
0.13391114343686755 0.0027400044401138034 0.007337423371365056
32.0263880482659 0.0848372466592608 0.4864388472750027
----


In [82]:
import numpy as np
np.set_printoptions(suppress=True)
h = 0.01
GainMatrix = np.zeros((3,3))

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''


[[ 26.533  -8.735  -2.02 ]
 [  0.191  -0.343   0.129]
 [ -1.881 -11.285 -10.754]]


' export later to latex table '

In [85]:
''' Gain matrix estimation without outliers '''
np.set_printoptions(suppress=True)
margin = 10

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['NT_MonReturns']-standard_coord['NT_MonReturns'].mean()) <= (margin*standard_coord['NT_MonReturns'].std())]
standard_coord_NT_Return = new_standard_coord['NT_MonReturns'].mean()

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['VI_MonReturns']-standard_coord['VI_MonReturns'].mean()) <= (margin*standard_coord['VI_MonReturns'].std())]
standard_coord_VI_Return = new_standard_coord['VI_MonReturns'].mean()

new_standard_coord = pd.DataFrame()
new_standard_coord = standard_coord[np.abs(standard_coord['TF_MonReturns']-standard_coord['TF_MonReturns'].mean()) <= (margin*standard_coord['TF_MonReturns'].std())]
standard_coord_TF_Return = new_standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)


new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['NT_MonReturns']-NT_bump_coord['NT_MonReturns'].mean()) <= (margin*NT_bump_coord['NT_MonReturns'].std())]
NT_bump_NT_Return = new_NT_bump_coord['NT_MonReturns'].mean()

new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['VI_MonReturns']-NT_bump_coord['VI_MonReturns'].mean()) <= (margin*NT_bump_coord['VI_MonReturns'].std())]
NT_bump_VI_Return = new_NT_bump_coord['VI_MonReturns'].mean()

new_NT_bump_coord = pd.DataFrame()
new_NT_bump_coord = NT_bump_coord[np.abs(NT_bump_coord['TF_MonReturns']-NT_bump_coord['TF_MonReturns'].mean()) <= (margin*NT_bump_coord['TF_MonReturns'].std())]
NT_bump_TF_Return = new_NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['NT_MonReturns']-VI_bump_coord['NT_MonReturns'].mean()) <= (margin*VI_bump_coord['NT_MonReturns'].std())]
VI_bump_NT_Return = new_VI_bump_coord['NT_MonReturns'].mean()

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['VI_MonReturns']-VI_bump_coord['VI_MonReturns'].mean()) <= (margin*VI_bump_coord['VI_MonReturns'].std())]
VI_bump_VI_Return = new_VI_bump_coord['VI_MonReturns'].mean()

new_VI_bump_coord = pd.DataFrame()
new_VI_bump_coord = VI_bump_coord[np.abs(VI_bump_coord['TF_MonReturns']-VI_bump_coord['TF_MonReturns'].mean()) <= (margin*VI_bump_coord['TF_MonReturns'].std())]
VI_bump_TF_Return = new_VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = TF_bump_coord[np.abs(TF_bump_coord['NT_MonReturns']-TF_bump_coord['NT_MonReturns'].mean()) <= (margin*TF_bump_coord['NT_MonReturns'].std())]
TF_bump_NT_Return = new_TF_bump_coord['NT_MonReturns'].mean()

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = TF_bump_coord[np.abs(TF_bump_coord['VI_MonReturns']-TF_bump_coord['VI_MonReturns'].mean()) <= (margin*TF_bump_coord['VI_MonReturns'].std())]
TF_bump_VI_Return = new_TF_bump_coord['VI_MonReturns'].mean()

new_TF_bump_coord = pd.DataFrame()
new_TF_bump_coord = VI_bump_coord[np.abs(TF_bump_coord['TF_MonReturns']-TF_bump_coord['TF_MonReturns'].mean()) <= (margin*TF_bump_coord['TF_MonReturns'].std())]
TF_bump_TF_Return = new_TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)




0.006137508227804286 0.0004972090530702269 0.003995113060921237
0.010184159274241432 -0.0004585142723309753 0.011201847906710792
0.0036678490676865048 -0.0015163113487066228 0.0001668875291123838
0.003722596198612407 0.0010311986816240268 0.002497036461375682


In [86]:
np.set_printoptions(suppress=True)
h = 0.01
GainMatrix = np.zeros((3,3))

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''

[[ 0.405 -0.247 -0.241]
 [-0.096 -0.201  0.053]
 [ 0.721 -0.383 -0.15 ]]


' export later to latex table '