In [32]:
import pandas as pd

standard_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_standard.csv")

standard_coord_NT_Return = standard_coord['NT_MonReturns'].mean()
standard_coord_VI_Return = standard_coord['VI_MonReturns'].mean()
standard_coord_TF_Return = standard_coord['TF_MonReturns'].mean()

print(standard_coord_NT_Return, standard_coord_VI_Return, standard_coord_TF_Return)

NT_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_NT_bump.csv")

NT_bump_NT_Return = NT_bump_coord['NT_MonReturns'].mean()
NT_bump_VI_Return = NT_bump_coord['VI_MonReturns'].mean()
NT_bump_TF_Return = NT_bump_coord['TF_MonReturns'].mean()

print(NT_bump_NT_Return, NT_bump_VI_Return, NT_bump_TF_Return)

VI_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_VI_bump.csv")

VI_bump_NT_Return = VI_bump_coord['NT_MonReturns'].mean()
VI_bump_VI_Return = VI_bump_coord['VI_MonReturns'].mean()
VI_bump_TF_Return = VI_bump_coord['TF_MonReturns'].mean()

print(VI_bump_NT_Return, VI_bump_VI_Return, VI_bump_TF_Return)

TF_bump_coord = pd.read_csv("/Users/aymericvie/Documents/GitHub/evology/evology/research/TransferStatus/GainMatrixSingle/data/static_TF_bump.csv")

TF_bump_NT_Return = TF_bump_coord['NT_MonReturns'].mean()
TF_bump_VI_Return = TF_bump_coord['VI_MonReturns'].mean()
TF_bump_TF_Return = TF_bump_coord['TF_MonReturns'].mean()

print(TF_bump_NT_Return, TF_bump_VI_Return, TF_bump_TF_Return)






0.0016380324901516105 0.002179044056434656 0.0024061264789541786
0.0004778099582153643 0.004157649429985359 0.011477691296262863
0.0015252637627596038 0.0012623999249932246 0.0010987359377023268
0.0012859377708756715 0.0022964755922302883 0.0014315685083081643


In [33]:
import numpy as np
np.set_printoptions(suppress=True)
h = 0.01
GainMatrix = np.zeros((3,3))

GainMatrix[0,0] = round(1/h * (NT_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,1] = round(1/h * (VI_bump_NT_Return - standard_coord_NT_Return),3)
GainMatrix[0,2] = round(1/h * (TF_bump_NT_Return - standard_coord_NT_Return),3)

GainMatrix[1,0] = round(1/h * (NT_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,1] = round(1/h * (VI_bump_VI_Return - standard_coord_VI_Return),3)
GainMatrix[1,2] = round(1/h * (TF_bump_VI_Return - standard_coord_VI_Return),3)

GainMatrix[2,0] = round(1/h * (NT_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,1] = round(1/h * (VI_bump_TF_Return - standard_coord_TF_Return),3)
GainMatrix[2,2] = round(1/h * (TF_bump_TF_Return - standard_coord_TF_Return),3)

print(GainMatrix)
''' export later to latex table '''

[[-0.116 -0.011 -0.035]
 [ 0.198 -0.092  0.012]
 [ 0.907 -0.131 -0.097]]


' export later to latex table '